### ISSUE TITLE
File upload fails with "AttributeError: module 'web3.eth' has no attribute 'Account'" error

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/pybundlr#20]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ana/venv/lib/python3.11/site-packages/pybundlr/pybundlr.py", line 141, in fund_and_upload
    addr = eth_address(private_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ana/venv/lib/python3.11/site-packages/pybundlr/pybundlr.py", line 203, in eth_address
    account = web3.eth.Account.from_key(eth_private_key)
              ^^^^^^^^^^^^^^^^
AttributeError: module 'web3.eth' has no attribute 'Account'

**Comment by cemdenizsel** [comment]
Hi, if you downgrade the web3 version to 5.28.0, it gets fixed. But it might be better to put a fixed library version rather than >=5.28.0 inside the requirements.txt

**Comment by trentmc** [comment]
FYI: as of Feb 2023, this library is not being maintained. If you encounter a bug, feel free to report it, but do not expect it to be fixed.  If you do a PR where tests pass, we're happy to merge it.  And feel free to fork this repo and change it as you wish (including bug fixes).
